### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x8007000E

### ISSUE THREAD

**Issue by Hanrepo** [miracum/fhir-pseudonymizer#104]
have tried to reserve memory: 4g, unfortunately it doesn't work. Has anyone such problem?

**Comment by chgl** [comment]
Not sure the mem_limit is still used in current compose versions. It should use the deploy: section instead: https://docs.docker.com/compose/compose-file/deploy/#memory - you can check whether the limits were set using docker stats. If your machine has a lot of CPUs, you might want to limit the available CPUs as well: each one increases the size of required memory by the application.

Can you share the details of where you're running the container if the above doesn't help. Docker version, os version, amount of ram and CPU.

**Comment by Hanrepo** [comment]
Docker version 24.0.6, build ed223bc
OS Information | linux x86_64 Ubuntu 22.04.3 LTS
Total CPU | 4
Total memory | 16.7 GB

Based on the Docker documentation, I made some modifications:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4g
          pids: 1
        reservations:
          cpus: '0.5'
          memory: 4g

**Comment by chgl** [comment]
Thats a strange issue. The setup looks fine.

It definitely wont with with pids limited to 1, in that case the error should be "0x80070008". Can you try removing the PID limitation and starting it again?

If that doesn't work, can you try launching an unmodified compose, the example one in https://github.com/miracum/fhir-pseudonymizer/blob/master/compose/compose.yaml. E.g. from the repository root, run:

```sh
docker compose -f compose/compose.yaml up
```

**Comment by Hanrepo** [comment]
Removing pids doesn't resolve the issue, good News is that it can be initiated with an unmodified compose.

**Comment by Hanrepo** [comment]
"
 SSL_CERT_FILE: "/opt/fhir-pseudonymizer/certs/nginx-selfsigned.crt"
      SSL_KEY_FILE: "/opt/fhir-pseudonymizer/certs/nginx-selfsigned.key"
    volumes:
      - "./anonymization.yaml:/opt/fhir-pseudonymizer/anonymization.yaml:ro"
      - "./certs/nginx-selfsigned.crt:/opt/fhir-pseudonymizer/certs/nginx-selfsigned.crt:ro"
      - "./certs/nginx-selfsigned.key:/opt/fhir-pseudonymizer/certs/nginx-selfsigned.key:ro"
"
using opt instead of /etc/,  then, it works.

**Comment by UKFr-DIZ** [comment]
Hi, 

from our site, we have the same issue. Although moving the anonymization.yaml didn't do anything for us. 
However, what worked for us, was setting the environment var `DOTNET_EnableDiagnostics: "0"`

based on here: https://stackoverflow.com/questions/76383522/asp-net-core-7-0-container-failed-to-create-coreclr-hresult-0x8007000e 

If I don't set that var, the container immediatly stop with the same error message in this issue. 
The server itself has enough RAM (16GB) and i didn't specify the available RAM for the container.

**Comment by chgl** [comment]
Thanks for sharing! Seems to very environment specific, but glad that worked. There's also an "official " compose sample which sets that env var as well in order to run on a read-only filesystem: https://github.com/miracum/fhir-pseudonymizer/blob/master/compose/compose.yaml
