### ISSUE TITLE
Crypto hashing a literal reference uri node

### ISSUE THREAD

**Issue by jabberwoc** [miracum/fhir-pseudonymizer#75]
There's a special case when using the `cryptoHash` method on literal references nodes:

> There is a special case when crypto hashing a [literal reference](https://www.hl7.org/fhir/references.html#literal) element. The tool captures and transforms only the id part from a reference, for example, reference Patient/123 will be hashed to Patient/a3c024f01cccb3b63457d848b0d2f89c1f744a3d. In this way, you can easily resolve references across anonymized FHIR resources.

However, this only covers reference string nodes. I would propose extending this feature to reference **uri** nodes like `Bundle.request.url`.

This would serve the same purpose (i.e. targeting resource ids). The gPAS pseudonymization processor which provides the same feature (for pseudonymization), already covers handling uri nodes. In my opinion, this feature is incomplete without handling those, as well.

@chgl What do you think?

**Comment by chgl** [comment]
You're right and adding it would definitely be more consistent. Ist this something you'd like to work on?
